package com.cafezin.agenda.view;

import com.cafezin.agenda.dao.CabelereiroDAO;
import com.cafezin.agenda.model.Cabeleireiro;

import javax.swing.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class cadastroCabeleireiro extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCabeleireiro
     */
    public cadastroCabeleireiro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoCafezin = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        buttonCadastrarCab = new javax.swing.JButton();
        dataNascField = new javax.swing.JTextField();
        dataNascLabel = new javax.swing.JLabel();
        anosProfissaoField = new javax.swing.JTextField();
        anosProfissaoLabel = new javax.swing.JLabel();
        especialidadeField = new javax.swing.JTextField();
        especialidadeLabel = new javax.swing.JLabel();
        horariosLabel = new javax.swing.JLabel();
        horariosField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        logoCafezin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Houston Barros\\Documents\\NetBeansProjects\\Agenda\\src\\main\\java\\resources\\images\\Cafezin.png")); // NOI18N

        nomeLabel.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        nomeLabel.setForeground(new java.awt.Color(145, 109, 75));
        nomeLabel.setText("Nome");

        nomeField.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        nomeField.setForeground(new java.awt.Color(145, 109, 75));
        nomeField.setDisabledTextColor(new java.awt.Color(145, 109, 75));
        nomeField.setSelectionColor(new java.awt.Color(145, 109, 75));

        buttonCadastrarCab.setBackground(new java.awt.Color(145, 109, 75));
        buttonCadastrarCab.setForeground(new java.awt.Color(255, 255, 255));
        buttonCadastrarCab.setText("Cadastrar Cabeleireiro");
        buttonCadastrarCab.setBorder(null);
        buttonCadastrarCab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarCabActionPerformed(evt);
            }
        });

        dataNascField.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        dataNascField.setForeground(new java.awt.Color(145, 109, 75));
        dataNascField.setDisabledTextColor(new java.awt.Color(145, 109, 75));
        dataNascField.setSelectionColor(new java.awt.Color(145, 109, 75));

        dataNascLabel.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        dataNascLabel.setForeground(new java.awt.Color(145, 109, 75));
        dataNascLabel.setText("Data de Nascimento");

        anosProfissaoField.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        anosProfissaoField.setForeground(new java.awt.Color(145, 109, 75));
        anosProfissaoField.setDisabledTextColor(new java.awt.Color(145, 109, 75));
        anosProfissaoField.setSelectionColor(new java.awt.Color(145, 109, 75));

        anosProfissaoLabel.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        anosProfissaoLabel.setForeground(new java.awt.Color(145, 109, 75));
        anosProfissaoLabel.setText("Anos de Profissão");

        especialidadeField.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        especialidadeField.setForeground(new java.awt.Color(145, 109, 75));
        especialidadeField.setDisabledTextColor(new java.awt.Color(145, 109, 75));
        especialidadeField.setSelectionColor(new java.awt.Color(145, 109, 75));

        especialidadeLabel.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        especialidadeLabel.setForeground(new java.awt.Color(145, 109, 75));
        especialidadeLabel.setText("Especialidade");

        horariosLabel.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        horariosLabel.setForeground(new java.awt.Color(145, 109, 75));
        horariosLabel.setText("Horários de Trabalho");

        horariosField.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        horariosField.setForeground(new java.awt.Color(145, 109, 75));
        horariosField.setDisabledTextColor(new java.awt.Color(145, 109, 75));
        horariosField.setSelectionColor(new java.awt.Color(145, 109, 75));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(31, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(especialidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(especialidadeLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(horariosField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(horariosLabel)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(nomeLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(dataNascLabel)
                                                        .addComponent(dataNascField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(anosProfissaoLabel)
                                                        .addComponent(anosProfissaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(34, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(buttonCadastrarCab, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(logoCafezin))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(logoCafezin)
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(nomeLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(dataNascLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(dataNascField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(anosProfissaoLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(anosProfissaoField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(especialidadeLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(especialidadeField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(horariosLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(horariosField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(24, 24, 24)
                                .addComponent(buttonCadastrarCab, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void buttonCadastrarCabActionPerformed(java.awt.event.ActionEvent evt) {
        if(nomeField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite um nome!");
            nomeField.requestFocus();
        } else if (dataNascField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite uma data de nascimento!");
            dataNascField.requestFocus();
        } else if (anosProfissaoField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite quanto tempo de profissão!");
            anosProfissaoField.requestFocus();
        } else if (especialidadeField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite a especialidade!");
            especialidadeField.requestFocus();
        } else if (horariosField.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Digite os horários de trabalho!");
            horariosField.requestFocus();
        } else {

            String nome = nomeField.getText();
            String dataNasc = dataNascField.getText();
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

            Date data = null;

            try {
                data = formato.parse(dataNasc);
            } catch (ParseException ex) {
                throw new RuntimeException(ex);
            }


            Integer anosProfissao = Integer.valueOf(anosProfissaoField.getText());
            String especialidade = especialidadeField.getText();
            String horarios = horariosField.getText();

            CabelereiroDAO cabeleireiroDao = new CabelereiroDAO();

            Cabeleireiro cabeleireiro = new Cabeleireiro();
            cabeleireiro.setNome(nome);
            cabeleireiro.setDataNasc(data);
            cabeleireiro.setAnosProfissao(anosProfissao);
            cabeleireiro.setEspecialidade(especialidade);
            cabeleireiro.setHorariosDeTrabalho(horarios);

            cabeleireiroDao.create(cabeleireiro);

            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField anosProfissaoField;
    private javax.swing.JLabel anosProfissaoLabel;
    private javax.swing.JButton buttonCadastrarCab;
    private javax.swing.JTextField dataNascField;
    private javax.swing.JLabel dataNascLabel;
    private javax.swing.JTextField especialidadeField;
    private javax.swing.JLabel especialidadeLabel;
    private javax.swing.JTextField horariosField;
    private javax.swing.JLabel horariosLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoCafezin;
    private javax.swing.JTextField nomeField;
    private javax.swing.JLabel nomeLabel;
    // End of variables declaration
}