package com.cafezin.agenda.view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import com.cafezin.agenda.dao.CabelereiroDAO;
import com.cafezin.agenda.dao.ClienteDAO;
import com.cafezin.agenda.model.Cabeleireiro;
import com.cafezin.agenda.model.Cliente;

import javax.swing.*;

import java.util.Arrays;

import static java.lang.String.*;

/**
 *
 * @author Houston Barros
 */
public class editarCliente extends javax.swing.JFrame {

    /**
     * Creates new form EditarCabeleireiro
     */
    public editarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        loginLabel2 = new javax.swing.JLabel();
        loginField3 = new javax.swing.JTextField();
        loginLabel3 = new javax.swing.JLabel();
        loginLabel4 = new javax.swing.JLabel();
        loginField4 = new javax.swing.JTextField();
        loginLabel = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        buttonCadastrarCab = new javax.swing.JButton();
        loginField1 = new javax.swing.JTextField();
        loginLabel1 = new javax.swing.JLabel();
        loginField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        logoCafezin = new javax.swing.JLabel();
        buttonPesquisarCabeleireiros = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        buttonDeletar = new javax.swing.JButton();
        buttonAtualizar = new javax.swing.JButton();
        nomeLabel = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        telefoneField = new javax.swing.JTextField();
        telefoneLabel = new javax.swing.JLabel();
        sexoLabel = new javax.swing.JLabel();
        selectSexo = new javax.swing.JComboBox<>();

        loginLabel2.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        loginLabel2.setForeground(new java.awt.Color(145, 109, 75));
        loginLabel2.setText("Anos de Profissão");

        loginField3.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        loginField3.setForeground(new java.awt.Color(145, 109, 75));
        loginField3.setDisabledTextColor(new java.awt.Color(145, 109, 75));
        loginField3.setSelectionColor(new java.awt.Color(145, 109, 75));

        loginLabel3.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        loginLabel3.setForeground(new java.awt.Color(145, 109, 75));
        loginLabel3.setText("Especialidade");

        loginLabel4.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        loginLabel4.setForeground(new java.awt.Color(145, 109, 75));
        loginLabel4.setText("Horários de Trabalho");

        loginField4.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        loginField4.setForeground(new java.awt.Color(145, 109, 75));
        loginField4.setDisabledTextColor(new java.awt.Color(145, 109, 75));
        loginField4.setSelectionColor(new java.awt.Color(145, 109, 75));

        loginLabel.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(145, 109, 75));
        loginLabel.setText("Nome");

        loginField.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        loginField.setForeground(new java.awt.Color(145, 109, 75));
        loginField.setDisabledTextColor(new java.awt.Color(145, 109, 75));
        loginField.setSelectionColor(new java.awt.Color(145, 109, 75));

        buttonCadastrarCab.setBackground(new java.awt.Color(145, 109, 75));
        buttonCadastrarCab.setForeground(new java.awt.Color(255, 255, 255));
        buttonCadastrarCab.setText("Cadastrar Cabeleireiro");
        buttonCadastrarCab.setBorder(null);

        loginField1.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        loginField1.setForeground(new java.awt.Color(145, 109, 75));
        loginField1.setDisabledTextColor(new java.awt.Color(145, 109, 75));
        loginField1.setSelectionColor(new java.awt.Color(145, 109, 75));

        loginLabel1.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        loginLabel1.setForeground(new java.awt.Color(145, 109, 75));
        loginLabel1.setText("Data de Nascimento");

        loginField2.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        loginField2.setForeground(new java.awt.Color(145, 109, 75));
        loginField2.setDisabledTextColor(new java.awt.Color(145, 109, 75));
        loginField2.setSelectionColor(new java.awt.Color(145, 109, 75));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        logoCafezin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Houston Barros\\Documents\\NetBeansProjects\\Agenda\\src\\main\\java\\resources\\images\\Cafezin.png")); // NOI18N

        buttonPesquisarCabeleireiros.setBackground(new java.awt.Color(145, 109, 75));
        buttonPesquisarCabeleireiros.setForeground(new java.awt.Color(255, 255, 255));
        buttonPesquisarCabeleireiros.setText("Pesquisar");
        buttonPesquisarCabeleireiros.setBorder(null);
        buttonPesquisarCabeleireiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPesquisarCabeleireirosActionPerformed(evt);
            }
        });

        idLabel.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        idLabel.setForeground(new java.awt.Color(145, 109, 75));
        idLabel.setText("ID");

        idField.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        idField.setForeground(new java.awt.Color(145, 109, 75));
        idField.setDisabledTextColor(new java.awt.Color(145, 109, 75));
        idField.setSelectionColor(new java.awt.Color(145, 109, 75));

        buttonDeletar.setBackground(new java.awt.Color(145, 109, 75));
        buttonDeletar.setForeground(new java.awt.Color(255, 255, 255));
        buttonDeletar.setText("Deletar Cliente");
        buttonDeletar.setBorder(null);
        buttonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeletarActionPerformed(evt);
            }
        });

        buttonAtualizar.setBackground(new java.awt.Color(145, 109, 75));
        buttonAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        buttonAtualizar.setText("Atualizar Cliente");
        buttonAtualizar.setBorder(null);
        buttonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtualizarActionPerformed(evt);
            }
        });

        nomeLabel.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        nomeLabel.setForeground(new java.awt.Color(145, 109, 75));
        nomeLabel.setText("Nome");

        nomeField.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        nomeField.setForeground(new java.awt.Color(145, 109, 75));
        nomeField.setDisabledTextColor(new java.awt.Color(145, 109, 75));
        nomeField.setSelectionColor(new java.awt.Color(145, 109, 75));

        telefoneField.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        telefoneField.setForeground(new java.awt.Color(145, 109, 75));
        telefoneField.setDisabledTextColor(new java.awt.Color(145, 109, 75));
        telefoneField.setSelectionColor(new java.awt.Color(145, 109, 75));

        telefoneLabel.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        telefoneLabel.setForeground(new java.awt.Color(145, 109, 75));
        telefoneLabel.setText("Telefone");

        sexoLabel.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        sexoLabel.setForeground(new java.awt.Color(145, 109, 75));
        sexoLabel.setText("Sexo");

        selectSexo.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        selectSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Masculino", "Feminino", "Outros" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(258, 258, 258)
                                                .addComponent(logoCafezin))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addContainerGap(86, Short.MAX_VALUE)
                                                .addComponent(buttonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(buttonDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(86, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(nomeLabel)
                                                        .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(telefoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(telefoneLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(sexoLabel)
                                                        .addComponent(selectSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(idLabel)
                                                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(buttonPesquisarCabeleireiros, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(101, 101, 101)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(logoCafezin)
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(idLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(buttonPesquisarCabeleireiros, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(nomeLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(telefoneLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(telefoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(selectSexo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(sexoLabel)
                                                .addGap(38, 38, 38)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buttonDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void buttonPesquisarCabeleireirosActionPerformed(java.awt.event.ActionEvent evt) {
        //Pegar o ID a ser pesquisado
        int idPesquisa = Integer.parseInt(idField.getText());
        ClienteDAO clienteDAO = new ClienteDAO();
        Cliente cliente = clienteDAO.selectCliente(idPesquisa);

        if(cliente == null){
            JOptionPane.showMessageDialog(this, "Cliente não encontrado");
        } else {
            nomeField.setText(cliente.getNome());
            selectSexo.setSelectedItem(cliente.getSexo());
            telefoneField.setText(valueOf(cliente.getTelefone()));
        }
    }

    private void buttonDeletarActionPerformed(java.awt.event.ActionEvent evt) {
        int idDeletar = Integer.parseInt(idField.getText());
        ClienteDAO clienteDAO = new ClienteDAO();
        Cliente cliente = clienteDAO.selectCliente(idDeletar);

        if(cliente == null){
            JOptionPane.showMessageDialog(this, "Cliente não encontrado");
        } else {
            clienteDAO.deleteByID(idDeletar);
            JOptionPane.showMessageDialog(null, "Cliente deletado com sucesso");
            nomeField.setText("");
            selectSexo.setSelectedItem("Selecione");
            telefoneField.setText("");
        }
    }

    private void buttonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {
        Cliente c1 = new Cliente();
        ClienteDAO clienteDAO = new ClienteDAO();

        String nome = nomeField.getText();
        String sexo = Arrays.toString(selectSexo.getSelectedObjects());

        // Removo os colchetes após tranformar o objeto em String
        sexo = sexo.replace("[", "");
        sexo = sexo.replace("]", "");

        String telefone = telefoneField.getText();
        Integer idCliente = Integer.valueOf(idField.getText());

        c1.setNome(nome);
        c1.setSexo(sexo);
        c1.setTelefone(telefone);
        c1.setIdCliente(idCliente);

        clienteDAO.update(c1);

        JOptionPane.showMessageDialog(null, "Cliente atualizado com sucesso!");

        nomeField.setText("");
        selectSexo.setSelectedItem("Selecione");
        telefoneField.setText("");
    }

    // Variables declaration - do not modify
    private javax.swing.JButton buttonAtualizar;
    private javax.swing.JButton buttonCadastrarCab;
    private javax.swing.JButton buttonDeletar;
    private javax.swing.JButton buttonPesquisarCabeleireiros;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField loginField;
    private javax.swing.JTextField loginField1;
    private javax.swing.JTextField loginField2;
    private javax.swing.JTextField loginField3;
    private javax.swing.JTextField loginField4;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel loginLabel1;
    private javax.swing.JLabel loginLabel2;
    private javax.swing.JLabel loginLabel3;
    private javax.swing.JLabel loginLabel4;
    private javax.swing.JLabel logoCafezin;
    private javax.swing.JTextField nomeField;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JComboBox<String> selectSexo;
    private javax.swing.JLabel sexoLabel;
    private javax.swing.JTextField telefoneField;
    private javax.swing.JLabel telefoneLabel;
    // End of variables declaration
}