package com.cafezin.agenda.view;

import static com.cafezin.agenda.view.visualizarCabeleireiros.preencherTabela;

public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logoCafezin1 = new javax.swing.JLabel();
        buttonCadastrarCabeleireiro = new javax.swing.JButton();
        buttonEditCabeleireiro = new javax.swing.JButton();
        buttonVisualizarCabeleireiros = new javax.swing.JButton();
        buttonCadastrarCliente = new javax.swing.JButton();
        buttonEditarCliente = new javax.swing.JButton();
        buttonVisualizarClientes = new javax.swing.JButton();
        buttonVisualizarHorarios = new javax.swing.JButton();
        buttonEditarHorario = new javax.swing.JButton();
        buttonAgendarHorario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        logoCafezin1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Houston Barros\\Documents\\NetBeansProjects\\Agenda\\src\\main\\java\\resources\\images\\Cafezin.png")); // NOI18N

        buttonCadastrarCabeleireiro.setBackground(new java.awt.Color(145, 109, 75));
        buttonCadastrarCabeleireiro.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        buttonCadastrarCabeleireiro.setForeground(new java.awt.Color(255, 255, 255));
        buttonCadastrarCabeleireiro.setText("Cadastrar Cabeleireiro");
        buttonCadastrarCabeleireiro.setBorder(null);
        buttonCadastrarCabeleireiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarCabeleireiroActionPerformed(evt);
            }
        });

        buttonEditCabeleireiro.setBackground(new java.awt.Color(145, 109, 75));
        buttonEditCabeleireiro.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        buttonEditCabeleireiro.setForeground(new java.awt.Color(255, 255, 255));
        buttonEditCabeleireiro.setText("Editar Cabeleireiro");
        buttonEditCabeleireiro.setBorder(null);
        buttonEditCabeleireiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditCabeleireiroActionPerformed(evt);
            }
        });

        buttonVisualizarCabeleireiros.setBackground(new java.awt.Color(145, 109, 75));
        buttonVisualizarCabeleireiros.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        buttonVisualizarCabeleireiros.setForeground(new java.awt.Color(255, 255, 255));
        buttonVisualizarCabeleireiros.setText("Visualizar Cabeleireiros");
        buttonVisualizarCabeleireiros.setBorder(null);
        buttonVisualizarCabeleireiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVisualizarCabeleireirosActionPerformed(evt);
            }
        });

        buttonCadastrarCliente.setBackground(new java.awt.Color(145, 109, 75));
        buttonCadastrarCliente.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        buttonCadastrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        buttonCadastrarCliente.setText("Cadastrar Cliente");
        buttonCadastrarCliente.setBorder(null);
        buttonCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarClienteActionPerformed(evt);
            }
        });

        buttonEditarCliente.setBackground(new java.awt.Color(145, 109, 75));
        buttonEditarCliente.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        buttonEditarCliente.setForeground(new java.awt.Color(255, 255, 255));
        buttonEditarCliente.setText("Editar Cliente");
        buttonEditarCliente.setBorder(null);
        buttonEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarClienteActionPerformed(evt);
            }
        });

        buttonVisualizarClientes.setBackground(new java.awt.Color(145, 109, 75));
        buttonVisualizarClientes.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        buttonVisualizarClientes.setForeground(new java.awt.Color(255, 255, 255));
        buttonVisualizarClientes.setText("Visualizar Clientes");
        buttonVisualizarClientes.setBorder(null);
        buttonVisualizarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVisualizarClientesActionPerformed(evt);
            }
        });

        buttonVisualizarHorarios.setBackground(new java.awt.Color(145, 109, 75));
        buttonVisualizarHorarios.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        buttonVisualizarHorarios.setForeground(new java.awt.Color(255, 255, 255));
        buttonVisualizarHorarios.setText("Visualizar Horários");
        buttonVisualizarHorarios.setBorder(null);
        buttonVisualizarHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVisualizarHorariosActionPerformed(evt);
            }
        });

        buttonEditarHorario.setBackground(new java.awt.Color(145, 109, 75));
        buttonEditarHorario.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        buttonEditarHorario.setForeground(new java.awt.Color(255, 255, 255));
        buttonEditarHorario.setText("Editar Horário");
        buttonEditarHorario.setBorder(null);
        buttonEditarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarHorarioActionPerformed(evt);
            }
        });

        buttonAgendarHorario.setBackground(new java.awt.Color(145, 109, 75));
        buttonAgendarHorario.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        buttonAgendarHorario.setForeground(new java.awt.Color(255, 255, 255));
        buttonAgendarHorario.setText("Agendar Horário");
        buttonAgendarHorario.setBorder(null);
        buttonAgendarHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgendarHorarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(logoCafezin1)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(buttonCadastrarCabeleireiro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(buttonEditCabeleireiro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(buttonVisualizarCabeleireiros, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                                .addComponent(buttonCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(buttonEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(buttonVisualizarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                                .addComponent(buttonAgendarHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(buttonEditarHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(buttonVisualizarHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(32, 32, 32))))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(logoCafezin1)
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buttonEditCabeleireiro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonCadastrarCabeleireiro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonVisualizarCabeleireiros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buttonEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonCadastrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonVisualizarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(buttonEditarHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonAgendarHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonVisualizarHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void buttonCadastrarCabeleireiroActionPerformed(java.awt.event.ActionEvent evt) {
        new cadastroCabeleireiro().setVisible(true);
    }

    private void buttonEditCabeleireiroActionPerformed(java.awt.event.ActionEvent evt) {
        new editarCabeleireiro().setVisible(true);
    }

    private void buttonVisualizarCabeleireirosActionPerformed(java.awt.event.ActionEvent evt) {
        visualizarCabeleireiros tela = new visualizarCabeleireiros();
        tela.setVisible(true);

        preencherTabela();
    }

    private void buttonCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {
        new cadastroCliente().setVisible(true);
    }

    private void buttonEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {
        new editarCliente().setVisible(true);
    }

    private void buttonVisualizarClientesActionPerformed(java.awt.event.ActionEvent evt) {
        visualizarClientes tela = new visualizarClientes();
        tela.setVisible(true);

        visualizarClientes.preencherTabela();
    }

    private void buttonVisualizarHorariosActionPerformed(java.awt.event.ActionEvent evt) {
        visualizarAgendamentos tela = new visualizarAgendamentos();
        tela.setVisible(true);

        visualizarAgendamentos.preencherTabela();
    }

    private void buttonEditarHorarioActionPerformed(java.awt.event.ActionEvent evt) {
        new editarAgendamento().setVisible(true);
    }

    private void buttonAgendarHorarioActionPerformed(java.awt.event.ActionEvent evt) {
        new agendamento().setVisible(true);
    }

    // Variables declaration - do not modify
    private javax.swing.JButton buttonAgendarHorario;
    private javax.swing.JButton buttonCadastrarCabeleireiro;
    private javax.swing.JButton buttonCadastrarCliente;
    private javax.swing.JButton buttonEditCabeleireiro;
    private javax.swing.JButton buttonEditarCliente;
    private javax.swing.JButton buttonEditarHorario;
    private javax.swing.JButton buttonVisualizarCabeleireiros;
    private javax.swing.JButton buttonVisualizarClientes;
    private javax.swing.JButton buttonVisualizarHorarios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logoCafezin1;
    // End of variables declaration
}

