package com.cafezin.agenda.view;

import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Houston Barros
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoCafezin = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        loginField = new javax.swing.JTextField();
        senhaLabel = new javax.swing.JLabel();
        senhaField = new javax.swing.JPasswordField();
        buttonLogar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        logoCafezin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Houston Barros\\Documents\\NetBeansProjects\\Agenda\\src\\main\\java\\resources\\images\\Cafezin.png")); // NOI18N

        loginLabel.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(145, 109, 75));
        loginLabel.setText("Login");

        loginField.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        loginField.setForeground(new java.awt.Color(145, 109, 75));
        loginField.setDisabledTextColor(new java.awt.Color(145, 109, 75));
        loginField.setSelectionColor(new java.awt.Color(145, 109, 75));

        senhaLabel.setFont(new java.awt.Font("Inter", 1, 12)); // NOI18N
        senhaLabel.setForeground(new java.awt.Color(145, 109, 75));
        senhaLabel.setText("Senha");

        senhaField.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        senhaField.setForeground(new java.awt.Color(145, 109, 75));
        senhaField.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        senhaField.setSelectionColor(new java.awt.Color(145, 109, 75));
        senhaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaFieldActionPerformed(evt);
            }
        });

        buttonLogar.setBackground(new java.awt.Color(145, 109, 75));
        buttonLogar.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogar.setText("Logar");
        buttonLogar.setBorder(null);
        buttonLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(199, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(senhaField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(loginLabel)
                                        .addComponent(senhaLabel)
                                        .addComponent(logoCafezin, javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(buttonLogar, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(logoCafezin)
                                .addGap(30, 30, 30)
                                .addComponent(loginLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(senhaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(senhaField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void senhaFieldActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void buttonLogarActionPerformed(java.awt.event.ActionEvent evt) {
        if(loginField.getText().equals("admin") && new String(senhaField.getPassword()).equals("admin")){

            JOptionPane.showMessageDialog(null, "Logado Com Sucesso!");

            setVisible(false);
            new inicio().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Login Inválido!");
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JButton buttonLogar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField loginField;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel logoCafezin;
    private javax.swing.JPasswordField senhaField;
    private javax.swing.JLabel senhaLabel;
    // End of variables declaration
}

