package com.cafezin.agenda.view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import com.cafezin.agenda.dao.AgendamentoDAO;
import com.cafezin.agenda.dao.ClienteDAO;
import com.cafezin.agenda.model.Agendamento;
import com.cafezin.agenda.model.Cliente;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;

/**
 *
 * @author Houston Barros
 */
public class visualizarAgendamentos extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCabeleireiro
     */
    public visualizarAgendamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        logoCafezin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAgendamentos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        logoCafezin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Houston Barros\\Documents\\NetBeansProjects\\Agenda\\src\\main\\java\\resources\\images\\Cafezin.png")); // NOI18N

        tabelaAgendamentos.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        tabelaAgendamentos.setForeground(new java.awt.Color(145, 109, 75));
        tabelaAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null},
                        {null, null, null, null, null, null, null, null, null}
                },
                new String [] {
                        "ID", "Cliente", "Profissional", "Serviço", "Horário", "Data", "Valor", "Forma de Pagamento", "Status"
                }
        ) {
            final Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            final boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaAgendamentos.setToolTipText("");
        tabelaAgendamentos.setFocusable(false);
        tabelaAgendamentos.setSelectionBackground(new java.awt.Color(145, 109, 75));
        tabelaAgendamentos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelaAgendamentos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaAgendamentos);
        if (tabelaAgendamentos.getColumnModel().getColumnCount() > 0) {
            tabelaAgendamentos.getColumnModel().getColumn(0).setResizable(false);
            tabelaAgendamentos.getColumnModel().getColumn(1).setResizable(false);
            tabelaAgendamentos.getColumnModel().getColumn(2).setResizable(false);
            tabelaAgendamentos.getColumnModel().getColumn(3).setResizable(false);
            tabelaAgendamentos.getColumnModel().getColumn(4).setResizable(false);
            tabelaAgendamentos.getColumnModel().getColumn(5).setResizable(false);
            tabelaAgendamentos.getColumnModel().getColumn(6).setResizable(false);
            tabelaAgendamentos.getColumnModel().getColumn(7).setResizable(false);
            tabelaAgendamentos.getColumnModel().getColumn(8).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(23, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(23, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logoCafezin)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(logoCafezin)
                                .addGap(34, 34, 34)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    public static void preencherTabela(){

        DefaultTableModel model = (DefaultTableModel) tabelaAgendamentos.getModel();
        model.setNumRows(0);

        Object[] colunas = new Object[9];

        Agendamento agendamento = new Agendamento();

        ArrayList<Agendamento> listaDeAgendamentos = new ArrayList<Agendamento>();

        listaDeAgendamentos = (ArrayList<Agendamento>) AgendamentoDAO.listarAgendamentos();

        for(int i = 0; i < listaDeAgendamentos.size(); i++){
            agendamento = listaDeAgendamentos.get(i);

            colunas[0] = agendamento.getIdAgenda();
            colunas[1] = agendamento.getIdCabelereiro();
            colunas[2] = agendamento.getIdCliente();
            colunas[3] = agendamento.getServico();
            colunas[4] = agendamento.getHora();
            colunas[5] = agendamento.getDataAgenda();
            colunas[6] = agendamento.getValor();
            colunas[7] = agendamento.getFormaPagamento();
            colunas[8] = agendamento.getStatusPG();

            model.addRow(colunas);
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoCafezin;
    public static javax.swing.JTable tabelaAgendamentos;
    // End of variables declaration
}