package com.cafezin.agenda.view;

import com.cafezin.agenda.dao.CabelereiroDAO;
import com.cafezin.agenda.model.Cabeleireiro;

import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;

public class visualizarCabeleireiros extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCabeleireiro
     */
    public visualizarCabeleireiros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        logoCafezin = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCabeleireiros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        logoCafezin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Houston Barros\\Documents\\NetBeansProjects\\Agenda\\src\\main\\java\\resources\\images\\Cafezin.png")); // NOI18N

        tabelaCabeleireiros.setFont(new java.awt.Font("Inter", 0, 12)); // NOI18N
        tabelaCabeleireiros.setForeground(new java.awt.Color(145, 109, 75));
        tabelaCabeleireiros.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                },
                new String [] {
                        "ID", "Nome", "Anos de Profissão", "Especialidade", "Horários de Trabalho"
                }
        ) {
            final Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            final boolean[] canEdit = new boolean [] {
                    false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCabeleireiros.setToolTipText("");
        tabelaCabeleireiros.setSelectionBackground(new java.awt.Color(145, 109, 75));
        tabelaCabeleireiros.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tabelaCabeleireiros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaCabeleireiros);
        if (tabelaCabeleireiros.getColumnModel().getColumnCount() > 0) {
            tabelaCabeleireiros.getColumnModel().getColumn(0).setResizable(false);
            tabelaCabeleireiros.getColumnModel().getColumn(1).setResizable(false);
            tabelaCabeleireiros.getColumnModel().getColumn(2).setResizable(false);
            tabelaCabeleireiros.getColumnModel().getColumn(3).setResizable(false);
            tabelaCabeleireiros.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(logoCafezin)
                                .addGap(250, 250, 250))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(logoCafezin)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    public static void preencherTabela(){

        DefaultTableModel model = (DefaultTableModel) tabelaCabeleireiros.getModel();
        model.setNumRows(0);

        Object[] colunas = new Object[5];

        Cabeleireiro cabeleireiro = new Cabeleireiro();

        ArrayList<Cabeleireiro> listaDeCabeleireiros = new ArrayList<Cabeleireiro>();

        listaDeCabeleireiros = (ArrayList<Cabeleireiro>) CabelereiroDAO.listarCabeleireiros();

        for(int i = 0; i < listaDeCabeleireiros.size(); i++){
            cabeleireiro = listaDeCabeleireiros.get(i);

            colunas[0] = cabeleireiro.getIdCabeleireiro();
            colunas[1] = cabeleireiro.getNome();
            colunas[2] = cabeleireiro.getAnosProfissao();
            colunas[3] = cabeleireiro.getEspecialidade();
            colunas[4] = cabeleireiro.getHorariosDeTrabalho();

            model.addRow(colunas);
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoCafezin;
    public static javax.swing.JTable tabelaCabeleireiros;
    // End of variables declaration
}